development: &dev
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: <%= ENV["PGUSER"] || ENV["USER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host:     <%= ENV["PGHOST"] %>
  port:     <%= ENV["PGPORT"] %>
  database: fanboy_development

test: &test
  <<: *dev
  database: fanboy_test

production:
  <<: *dev
  database: fanboy_production
